name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint and tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Check
        run: cargo check

      - name: Clippy
        run: cargo clippy

      - name: Test
        run: cargo test
